import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'ubean';
import UiResolver from '../../packages/ui/src/resolver';
import { SHIKI_THEMES } from './src/shared/shiki-config';
import { collectPrerenderRoutes } from './build/docs-routes';
import { createMarkdownHighlight } from './build/highlight';

const rootDir = path.dirname(fileURLToPath(import.meta.url));

const highlightCode = await createMarkdownHighlight();

/**
 * Concrete prerender routes: static shell pages + default-locale content slugs
 * (+ zh-only pages) mapped through the shared route model in `build/docs-routes.ts`.
 * Dynamic param routes are not expanded by `prerender.all`, so content must be
 * listed explicitly; the `/zh` mirrors are generated by the SSG renderer's
 * `expandRoutes` (ubean@0.4.5, prefix_except_default) instead of being listed.
 */
const prerenderRoutes = await collectPrerenderRoutes(rootDir);

export default defineConfig({
  mode: 'ssg',
  favicon: 'https://r2.veanui.com/imgs/logo-vean-ui.svg?v=202609141212',
  i18n: {
    defaultLocale: 'en',
    locales: [
      { code: 'en', language: 'en', name: 'English' },
      { code: 'zh', language: 'zh-CN', name: '中文', dir: 'ltr' }
    ],
    strategy: 'prefix_except_default'
  },
  markdown: {
    wrapperClass: 'markdown-wrapper',
    theme: {
      light: SHIKI_THEMES.light,
      dark: SHIKI_THEMES.dark
    },
    markdownExit: {
      highlight: highlightCode
    }
  },
  components: {
    resolvers: [UiResolver()]
  },
  autoImports: {
    vueRouter: true,
    vueI18n: true
  },
  // Theme state is owned by @vean/theme (createThemeInitScript in app.ts);
  // disabling the built-in colorMode avoids a second, conflicting source.
  colorMode: false,
  // Full-text content search (@ubean/content, ubean@0.4.7).
  // Each locale is its own collection so the client can filter by the active
  // language: `__search.json` becomes `{ en: [...], zh: [...] }`. The zh source
  // gets a `/zh` prefix so hit ids already carry the `prefix_except_default`
  // locale prefix; the default (en) ids stay unprefixed.
  content: {
    sources: {
      en: { dir: 'src/content/en' },
      zh: { dir: 'src/content/zh', prefix: '/zh' }
    }
  },
  prerender: {
    include: prerenderRoutes,
    crawlLinks: true
  },
  dev: {
    host: '0.0.0.0'
  }
});
