export const components = {
  accordion: [
    'AccordionCompact',
    'AccordionRoot',
    'AccordionItem',
    'AccordionHeader',
    'AccordionTrigger',
    'AccordionContent',
    'AccordionDescription'
  ],
  affix: ['AffixCompact', 'AffixRoot', 'AffixPlaceholder', 'AffixContent'],
  alert: ['AlertCompact', 'AlertRoot', 'AlertContent', 'AlertTitle', 'AlertDescription', 'AlertClose'],
  anchor: ['AnchorCompact', 'AnchorItemCompact', 'AnchorLink', 'AnchorRoot'],
  arrow: ['Arrow'],
  aspectRatio: ['AspectRatio'],
  autocomplete: [
    'AutocompleteCompact',
    'AutocompleteRoot',
    'AutocompleteAnchor',
    'AutocompleteInput',
    'AutocompleteTrigger',
    'AutocompletePortal',
    'AutocompleteContent',
    'AutocompleteViewport',
    'AutocompleteGroup',
    'AutocompleteGroupLabel',
    'AutocompleteItem',
    'AutocompleteItemIndicator',
    'AutocompleteSeparator'
  ],
  avatar: ['AvatarCompact', 'AvatarRoot', 'AvatarImage', 'AvatarFallback'],
  backtop: ['Backtop'],
  breadcrumb: [
    'BreadcrumbRoot',
    'BreadcrumbCompact',
    'BreadcrumbList',
    'BreadcrumbItem',
    'BreadcrumbLink',
    'BreadcrumbPage',
    'BreadcrumbSeparator',
    'BreadcrumbEllipsis'
  ],
  button: ['Button', 'ButtonGroup'],
  calendar: [
    'CalendarCompact',
    'CalendarRoot',
    'CalendarHeader',
    'CalendarHeading',
    'CalendarPrev',
    'CalendarNext',
    'CalendarGrid',
    'CalendarGridHead',
    'CalendarGridBody',
    'CalendarGridRow',
    'CalendarHeadCell',
    'CalendarCell',
    'CalendarCellTrigger'
  ],
  calendarRange: [
    'CalendarRangeCompact',
    'CalendarRangeRoot',
    'CalendarRangeHeader',
    'CalendarRangeHeading',
    'CalendarRangePrev',
    'CalendarRangeNext',
    'CalendarRangeGrid',
    'CalendarRangeGridHead',
    'CalendarRangeGridBody',
    'CalendarRangeGridRow',
    'CalendarRangeHeadCell',
    'CalendarRangeCell',
    'CalendarRangeCellTrigger'
  ],
  carousel: [
    'CarouselCompact',
    'CarouselRoot',
    'CarouselContent',
    'CarouselContainer',
    'CarouselItem',
    'CarouselControl',
    'CarouselNavigation',
    'CarouselNext',
    'CarouselPrevious'
  ],
  cascader: [
    'CascaderRoot',
    'CascaderTrigger',
    'CascaderValue',
    'CascaderSearchInput',
    'CascaderContent',
    'CascaderMenu',
    'CascaderOption',
    'CascaderEmpty',
    'CascaderTags',
    'CascaderClear',
    'CascaderCompact'
  ],
  checkbox: [
    'CheckboxCompact',
    'CheckboxCardCompact',
    'CheckboxGroupCompact',
    'CheckboxCardGroupCompact',
    'CheckboxGroupRoot',
    'CheckboxRoot',
    'CheckboxControl',
    'CheckboxIndicator',
    'CheckboxLabel'
  ],
  clipboard: ['Clipboard'],
  collapsible: ['CollapsibleRoot', 'CollapsibleContent', 'CollapsibleTrigger'],
  colorArea: ['ColorAreaCompact', 'ColorAreaRoot', 'ColorAreaArea', 'ColorAreaThumb'],
  colorField: ['ColorFieldCompact', 'ColorFieldRoot', 'ColorFieldInput'],
  colorPicker: ['ColorPickerCompact', 'ColorPickerRoot', 'ColorPickerTrigger'],
  colorSlider: ['ColorSliderCompact', 'ColorSliderRoot', 'ColorSliderTrack', 'ColorSliderThumb'],
  colorSwatch: ['ColorSwatchCompact', 'ColorSwatchRoot', 'ColorSwatchChecker', 'ColorSwatchFill'],
  colorSwatchPicker: [
    'ColorSwatchPickerCompact',
    'ColorSwatchPickerRoot',
    'ColorSwatchPickerItem',
    'ColorSwatchPickerItemIndicator',
    'ColorSwatchPickerItemSwatch'
  ],
  combobox: [
    'ComboboxCompact',
    'ComboboxRoot',
    'ComboboxAnchor',
    'ComboboxTrigger',
    'ComboboxPortal',
    'ComboboxViewport',
    'ComboboxContent',
    'ComboboxCancel',
    'ComboboxClear',
    'ComboboxValue',
    'ComboboxArrow',
    'ComboboxGroup',
    'ComboboxGroupLabel',
    'ComboboxInput',
    'ComboboxItem',
    'ComboboxItemIndicator',
    'ComboboxEmpty',
    'ComboboxSeparator',
    'ComboboxVirtualizer'
  ],
  command: ['CommandCompact'],
  configProvider: ['ConfigProvider'],
  contextMenu: [
    'ContextMenuRoot',
    'ContextMenuTrigger',
    'ContextMenuPortal',
    'ContextMenuContent',
    'ContextMenuAnchor',
    'ContextMenuArrow',
    'ContextMenuGroup',
    'ContextMenuGroupLabel',
    'ContextMenuItem',
    'ContextMenuItemIndicator',
    'ContextMenuCheckboxItem',
    'ContextMenuRadioItem',
    'ContextMenuSub',
    'ContextMenuSubTrigger',
    'ContextMenuSubContent',
    'ContextMenuSeparator',
    'ContextMenuCheckboxGroup',
    'ContextMenuRadioGroup',
    'ContextMenuCompact',
    'ContextMenuCheckboxCompact',
    'ContextMenuRadioCompact',
    'ContextMenuWrapperCompact'
  ],
  dateField: ['DateFieldCompact', 'DateFieldRoot', 'DateFieldInput'],
  datePicker: ['DatePickerCompact'],
  dateRangeField: ['DateRangeFieldCompact', 'DateRangeFieldRoot', 'DateRangeFieldInput'],
  dateRangePicker: ['DateRangePickerCompact'],
  dialog: [
    'DialogCompact',
    'DialogProvider',
    'DialogRoot',
    'DialogTrigger',
    'DialogPortal',
    'DialogOverlay',
    'DialogPopup',
    'DialogHeader',
    'DialogContent',
    'DialogTitle',
    'DialogDescription',
    'DialogFooter',
    'DialogClose',
    'DialogFullscreen',
    'DialogCancel',
    'DialogConfirm'
  ],
  drawer: [
    'DrawerPortal',
    'DrawerCompact',
    'DrawerRoot',
    'DrawerRootNested',
    'DrawerTrigger',
    'DrawerPopup',
    'DrawerOverlay',
    'DrawerViewport',
    'DrawerSwipeArea',
    'DrawerHandle',
    'DrawerIndent',
    'DrawerIndentBackground',
    'DrawerHeader',
    'DrawerContent',
    'DrawerFooter',
    'DrawerTitle',
    'DrawerDescription',
    'DrawerClose',
    'DrawerCancel',
    'DrawerConfirm'
  ],
  dropdownMenu: [
    'DropdownMenuRoot',
    'DropdownMenuTrigger',
    'DropdownMenuPortal',
    'DropdownMenuContent',
    'DropdownMenuAnchor',
    'DropdownMenuArrow',
    'DropdownMenuGroup',
    'DropdownMenuGroupLabel',
    'DropdownMenuItem',
    'DropdownMenuItemIndicator',
    'DropdownMenuCheckboxItem',
    'DropdownMenuRadioItem',
    'DropdownMenuSub',
    'DropdownMenuSubTrigger',
    'DropdownMenuSubContent',
    'DropdownMenuSeparator',
    'DropdownMenuCheckboxGroup',
    'DropdownMenuRadioGroup',
    'DropdownMenuCompact',
    'DropdownMenuCheckboxCompact',
    'DropdownMenuRadioCompact',
    'DropdownMenuWrapperCompact'
  ],
  editable: [
    'EditableArea',
    'EditableCancelTrigger',
    'EditableEditTrigger',
    'EditableInput',
    'EditablePreview',
    'EditableRoot',
    'EditableSubmitTrigger',
    'EditableCompact'
  ],
  form: [
    'FormCompact',
    'FormFieldCompact',
    'FormFieldArrayCompact',
    'FormFieldBaseCompact',
    'FormField',
    'FormLabel',
    'FormControl',
    'FormDescription',
    'FormError'
  ],
  hoverCard: [
    'HoverCardRoot',
    'HoverCardTrigger',
    'HoverCardPortal',
    'HoverCardPositioner',
    'HoverCardPopup',
    'HoverCardArrow',
    'HoverCardCompact'
  ],
  input: ['InputCompact', 'InputRoot', 'InputControl', 'InputClear'],
  inputNumber: [
    'InputNumberCompact',
    'InputNumberRoot',
    'InputNumberControl',
    'InputNumberIncrement',
    'InputNumberDecrement',
    'InputNumberClear'
  ],
  inputOtp: ['InputOtpCompact', 'InputOtpInput', 'InputOtpPositioner', 'InputOtpRoot'],
  kbd: ['Kbd'],
  label: ['Label'],
  layout: [
    'LayoutCompact',
    'LayoutRoot',
    'LayoutSidebar',
    'LayoutRail',
    'LayoutMain',
    'LayoutHeader',
    'LayoutTab',
    'LayoutContent',
    'LayoutFooter',
    'LayoutMobile',
    'LayoutPlaceholder',
    'LayoutTrigger'
  ],
  link: ['Link'],
  listbox: [
    'ListboxRoot',
    'ListboxContent',
    'ListboxGroup',
    'ListboxGroupLabel',
    'ListboxItem',
    'ListboxItemIndicator',
    'ListboxFilter',
    'ListboxVirtualizer'
  ],
  menu: [
    'MenuRoot',
    'MenuPortal',
    'MenuContent',
    'MenuAnchor',
    'MenuArrow',
    'MenuGroup',
    'MenuGroupLabel',
    'MenuItem',
    'MenuItemIndicator',
    'MenuCheckboxItem',
    'MenuRadioItem',
    'MenuSub',
    'MenuSubTrigger',
    'MenuSubContent',
    'MenuSeparator',
    'MenuCheckboxGroup',
    'MenuRadioGroup',
    'MenuOptionCompact',
    'MenuOptionsCompact',
    'MenuCheckboxOptionsCompact',
    'MenuRadioOptionsCompact'
  ],
  menubar: [
    'MenubarRoot',
    'MenubarMenu',
    'MenubarTrigger',
    'MenubarPortal',
    'MenubarContent',
    'MenubarArrow',
    'MenubarGroup',
    'MenubarGroupLabel',
    'MenubarItem',
    'MenubarItemIndicator',
    'MenubarCheckboxItem',
    'MenubarRadioItem',
    'MenubarSub',
    'MenubarSubTrigger',
    'MenubarSubContent',
    'MenubarSeparator',
    'MenubarCheckboxGroup',
    'MenubarRadioGroup',
    'MenubarCompact',
    'MenubarMenus'
  ],
  navMenu: [
    'NavMenuCompact',
    'NavMenuRoot',
    'NavMenuList',
    'NavMenuItem',
    'NavMenuTrigger',
    'NavMenuContent',
    'NavMenuLink',
    'NavMenuViewport',
    'NavMenuSubTrigger',
    'NavMenuSubContent',
    'NavMenuOptionCompact'
  ],
  pageTabs: ['PageTabsRoot', 'PageTabsItem', 'PageTabsClose', 'PageTabsPin', 'PageTabsCompact'],
  pagination: [
    'PaginationRoot',
    'PaginationList',
    'PaginationListItem',
    'PaginationFirst',
    'PaginationPrev',
    'PaginationNext',
    'PaginationLast',
    'PaginationEllipsis',
    'PaginationCompact'
  ],
  password: ['PasswordCompact'],
  popconfirm: [
    'PopconfirmCompact',
    'PopconfirmRoot',
    'PopconfirmTrigger',
    'PopconfirmAnchor',
    'PopconfirmPositioner',
    'PopconfirmPopup',
    'PopconfirmClose',
    'PopconfirmHeader',
    'PopconfirmTitle',
    'PopconfirmDescription',
    'PopconfirmContent',
    'PopconfirmFooter',
    'PopconfirmConfirm',
    'PopconfirmCancel',
    'PopconfirmArrow',
    'PopconfirmPortal'
  ],
  popover: [
    'PopoverCompact',
    'PopoverRoot',
    'PopoverTrigger',
    'PopoverAnchor',
    'PopoverPositioner',
    'PopoverPopup',
    'PopoverClose',
    'PopoverArrow',
    'PopoverPortal'
  ],
  popper: [
    'PopperRoot',
    'PopperTrigger',
    'PopperAnchor',
    'PopperSubTrigger',
    'PopperPortal',
    'PopperPositioner',
    'PopperPositionerImpl',
    'PopperPopup',
    'PopperArrow',
    'PopperSub',
    'PopperCompact',
    'PopperPositioningRoot',
    'PopperPositioningPositioner',
    'PopperPositioningPopup'
  ],
  portal: ['Portal'],
  primitive: ['Primitive'],
  progress: [
    'ProgressProvider',
    'ProgressCompact',
    'ProgressCircleCompact',
    'ProgressRoot',
    'ProgressIndicator',
    'ProgressCircle'
  ],
  radioGroup: [
    'RadioGroupCompact',
    'RadioGroupCardCompact',
    'RadioGroupRoot',
    'RadioGroupItem',
    'RadioGroupControl',
    'RadioGroupIndicator',
    'RadioGroupLabel'
  ],
  rating: ['RatingItem', 'RatingRoot'],
  scrollArea: [
    'ScrollAreaRoot',
    'ScrollAreaViewport',
    'ScrollAreaScrollbar',
    'ScrollAreaThumb',
    'ScrollAreaCorner',
    'ScrollAreaCompact'
  ],
  segment: ['SegmentRoot', 'SegmentList', 'SegmentTrigger', 'SegmentIndicator', 'SegmentCompact'],
  select: [
    'SelectRoot',
    'SelectCompact',
    'SelectTrigger',
    'SelectClear',
    'SelectPortal',
    'SelectContent',
    'SelectViewport',
    'SelectGroup',
    'SelectGroupLabel',
    'SelectItem',
    'SelectItemIndicator',
    'SelectItemText',
    'SelectValue',
    'SelectTriggerIcon',
    'SelectScrollUpButton',
    'SelectScrollDownButton',
    'SelectSeparator',
    'SelectArrow'
  ],
  separator: ['SeparatorCompact', 'SeparatorRoot', 'SeparatorLabel'],
  slider: ['SliderCompact', 'SliderRoot', 'SliderTrack', 'SliderRange', 'SliderThumb'],
  slot: ['Slot'],
  splitNav: ['SplitNavRoot'],
  splitter: ['SplitterGroup', 'SplitterPanel', 'SplitterResizeHandle'],
  stepper: [
    'StepperRoot',
    'StepperItem',
    'StepperTrigger',
    'StepperIndicator',
    'StepperSeparator',
    'StepperTitle',
    'StepperDescription',
    'StepperCompact'
  ],
  switch: ['SwitchRoot', 'SwitchControl', 'SwitchThumb', 'SwitchCompact'],
  table: [
    'TableCompact',
    'TableRoot',
    'TableScroll',
    'TableContent',
    'TableHeader',
    'TableBody',
    'TableFooter',
    'TableRow',
    'TableHead',
    'TableCell',
    'TableCompactHead',
    'TableCompactRow',
    'TableVirtualSpacerRow'
  ],
  tabs: ['TabsRoot', 'TabsList', 'TabsTrigger', 'TabsContent', 'TabsIndicator', 'TabsCompact'],
  tagsInput: [
    'TagsInputCompact',
    'TagsInputRoot',
    'TagsInputItem',
    'TagsInputItemText',
    'TagsInputItemDelete',
    'TagsInputControl',
    'TagsInputClear'
  ],
  textarea: ['TextareaCompact', 'TextareaRoot', 'TextareaControl', 'TextareaClear', 'TextareaCounter'],
  timeField: ['TimeFieldCompact', 'TimeFieldRoot', 'TimeFieldInput'],
  timeRangeField: ['TimeRangeFieldCompact', 'TimeRangeFieldRoot', 'TimeRangeFieldInput'],
  toast: ['Toaster', 'ToastProvider'],
  toggle: ['Toggle'],
  toggleGroup: ['ToggleGroupRoot', 'ToggleGroupItem'],
  toolbar: [
    'ToolbarRoot',
    'ToolbarButton',
    'ToolbarLink',
    'ToolbarSeparator',
    'ToolbarToggleGroup',
    'ToolbarToggleItem'
  ],
  tooltip: [
    'TooltipCompact',
    'TooltipProvider',
    'TooltipRoot',
    'TooltipTrigger',
    'TooltipPortal',
    'TooltipPositioner',
    'TooltipPopup',
    'TooltipArrow'
  ],
  tree: ['TreeRoot', 'TreeItem', 'TreeVirtualizerRoot', 'TreeVirtualizerItem'],
  treeMenu: [
    'TreeMenuCompact',
    'TreeMenuOptionsCompact',
    'TreeMenuOptionCompact',
    'TreeMenuSlotCompact',
    'TreeMenuRoot',
    'TreeMenuGroupRoot',
    'TreeMenuGroup',
    'TreeMenuGroupLabel',
    'TreeMenuItem',
    'TreeMenuButton',
    'TreeMenuCollapsible',
    'TreeMenuSub'
  ],
  treeNav: ['TreeNavRoot', 'TreeNavOverflow', 'TreeNavOptionCompact', 'TreeNavOptionsCompact', 'TreeNavCompact'],
  virtualizer: ['VirtualizerRoot', 'VirtualizerContent', 'VirtualizerItem'],
  visuallyHidden: ['VisuallyHidden', 'VisuallyHiddenInput'],
  watermark: ['WatermarkCompact', 'WatermarkOverlay', 'WatermarkRoot']
};
